### ISSUE TITLE
Bug in LocaleBehavior.

### ISSUE THREAD

**Issue by Kharalampidi** [trntv/yii2-starter-kit#161]
Добрый день!
Вот в этом месте происходит ошибка https://github.com/trntv/yii2-starter-kit/blob/master/common/behaviors/LocaleBehavior.php#L47 , если пользователь авторизирован. 
Подсказать не могу ничего, т.к. не пойму, зачем там хелпер( 

```
exception 'yii\base\ErrorException' with message 'strrpos() expects parameter 1 to be string, object given' in /var/www/maritime/vendor/yiisoft/yii2/helpers/BaseArrayHelper.php:196
Stack trace:
#0 /var/www/maritime/common/behaviors/LocaleBehavior.php(47): yii\helpers\BaseArrayHelper::getValue()
#1 /var/www/maritime/vendor/yiisoft/yii2/base/Component.php(541): common\behaviors\LocaleBehavior->beforeRequest()
#2 /var/www/maritime/vendor/yiisoft/yii2/base/Component.php(541): ::call_user_func:{/var/www/maritime/vendor/yiisoft/yii2/base/Component.php:541}()
#3 /var/www/maritime/vendor/yiisoft/yii2/base/Application.php(372): yii\base\Component->trigger()
#4 /var/www/maritime/frontend/web/index.php(22): yii\base\Application->run()
#5 {main}
```

**Comment by Kharalampidi** [comment]
```php
if (!Yii::$app->user->isGuest && Yii::$app->user->getIdentity()->userProfile->locale != null)
```
Это имелось ввиду?

**Comment by trntv** [comment]
Ага, это. Никогда не стоит ничего делать в спешке :-) Спасибо, исправил.
