### ISSUE TITLE
Testing initial install fails

### ISSUE THREAD

**Issue by davidjeddy** [trntv/yii2-starter-kit#472]
Following the directions provided by ./docs/testing.md:
1) Create DB schema
2) Update .env with connection data
3) Run installer via `php tests/codeception/bin/yii app/setup` (added --interactive=0 setting)

Results are as follows:

``` BASH
[vagrant@localhost app-name]$ php tests/codeception/bin/yii app/setup --interactive=0
Setting writable: /app/path/app-name/common/runtime
Setting writable: /app/path/app-name/frontend/runtime
Setting writable: /app/path/app-name/frontend/web/assets
Setting writable: /app/path/app-name/backend/runtime
Setting writable: /app/path/app-name/backend/web/assets
Setting writable: /app/path/app-name/storage/cache
Setting writable: /app/path/app-name/storage/web/source
Setting executable: /app/path/app-name/backend/yii
Setting executable: /app/path/app-name/frontend/yii
Setting executable: /app/path/app-name/console/yii
Generating keys in /app/path/app-name/.env
Yii Migration Tool (based on Yii v2.0.10-dev)

Total 12 new migrations to be applied:
    m140703_123803_article
    m140703_123813_rbac
    m140709_173306_widget_menu
    m140709_173333_widget_text
    m140712_123329_widget_carousel
    m140805_084745_key_storage_item
    m141012_101932_i18n_tables
    m150318_213934_file_storage_item
    m150414_195800_timeline_event
    m150725_192740_seed_data
    m150929_074021_article_attachment_order
    m160203_095604_user_token

*** applying m140703_123803_article
    > create table {{%article_category}} ...Exception: SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'article_category' already exists
The SQL being executed was: CREATE TABLE `article_category` (
    `id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `slug` varchar(1024) NOT NULL,
    `title` varchar(512) NOT NULL,
    `body` text,
    `parent_id` int(11),
    `status` smallint(6) NOT NULL DEFAULT 0,
    `created_at` int(11),
    `updated_at` int(11)
) CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE=InnoDB (/app/path/app-name/vendor/yiisoft/yii2/db/Schema.php:633)
#0 /app/path/app-name/vendor/yiisoft/yii2/db/Command.php(854): yii\db\Schema->convertException(Object(PDOException), 'CREATE TABLE `a...')
#1 /app/path/app-name/vendor/yiisoft/yii2/db/Migration.php(260): yii\db\Command->execute()
#2 /app/path/app-name/common/migrations/db/m140703_123803_article.php(24): yii\db\Migration->createTable('{{%article_cate...', Array, 'CHARACTER SET u...')
#3 /app/path/app-name/vendor/yiisoft/yii2/db/Migration.php(93): m140703_123803_article->safeUp()
#4 /app/path/app-name/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(509): yii\db\Migration->up()
#5 /app/path/app-name/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(130): yii\console\controllers\BaseMigrateController->migrateUp('m140703_123803_...')
#6 [internal function]: yii\console\controllers\BaseMigrateController->actionUp(0)
#7 /app/path/app-name/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)
#8 /app/path/app-name/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\InlineAction->runWithParams(Array)
#9 /app/path/app-name/vendor/yiisoft/yii2/console/Controller.php(127): yii\base\Controller->runAction('up', Array)
#10 /app/path/app-name/vendor/yiisoft/yii2/base/Module.php(454): yii\console\Controller->runAction('up', Array)
#11 /app/path/app-name/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/up', Array)
#12 /app/path/app-name/console/controllers/AppController.php(39): yii\console\Application->runAction('migrate/up', Array)
#13 [internal function]: console\controllers\AppController->actionSetup()
#14 /app/path/app-name/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)
#15 /app/path/app-name/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\InlineAction->runWithParams(Array)
#16 /app/path/app-name/vendor/yiisoft/yii2/console/Controller.php(127): yii\base\Controller->runAction('setup', Array)
#17 /app/path/app-name/vendor/yiisoft/yii2/base/Module.php(454): yii\console\Controller->runAction('setup', Array)
#18 /app/path/app-name/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('app/setup', Array)
#19 /app/path/app-name/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('app/setup', Array)
#20 /app/path/app-name/vendor/yiisoft/yii2/base/Application.php(375): yii\console\Application->handleRequest(Object(yii\console\Request))
#21 /app/path/app-name/tests/codeception/bin/yii(22): yii\base\Application->run()
#22 {main}
*** failed to apply m140703_123803_article (time: 0.018s)


0 from 12 migrations were applied.

Migration failed. The rest of the migrations are canceled.
Yii Migration Tool (based on Yii v2.0.10-dev)

Total 3 new migrations to be applied:
    m150625_214101_roles
    m150625_215624_init_permissions
    m151223_074604_edit_own_model

*** applying m150625_214101_roles
Exception 'yii\db\Exception' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'app_test_db.rbac_auth_assignment' doesn't exist
The SQL being executed was: DELETE FROM `rbac_auth_assignment`'

in /app/path/app-name/vendor/yiisoft/yii2/db/Schema.php:633

Error Info:
Array
(
    [0] => 42S02
    [1] => 1146
    [2] => Table 'app_test_db.rbac_auth_assignment' doesn't exist
)

Stack trace:
#0 /app/path/app-name/vendor/yiisoft/yii2/db/Command.php(854): yii\db\Schema->convertException(Object(PDOException), 'DELETE FROM `rb...')
#1 /app/path/app-name/vendor/yiisoft/yii2/rbac/DbManager.php(918): yii\db\Command->execute()
#2 /app/path/app-name/vendor/yiisoft/yii2/rbac/DbManager.php(844): yii\rbac\DbManager->removeAllAssignments()
#3 /app/path/app-name/common/migrations/rbac/m150625_214101_roles.php(10): yii\rbac\DbManager->removeAll()
#4 /app/path/app-name/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(509): m150625_214101_roles->up()
#5 /app/path/app-name/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(130): yii\console\controllers\BaseMigrateController->migrateUp('m150625_214101_...')
#6 [internal function]: yii\console\controllers\BaseMigrateController->actionUp(0)
#7 /app/path/app-name/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)
#8 /app/path/app-name/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\InlineAction->runWithParams(Array)
#9 /app/path/app-name/vendor/yiisoft/yii2/console/Controller.php(127): yii\base\Controller->runAction('up', Array)
#10 /app/path/app-name/vendor/yiisoft/yii2/base/Module.php(454): yii\console\Controller->runAction('up', Array)
#11 /app/path/app-name/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('rbac-migrate/up', Array)
#12 /app/path/app-name/console/controllers/AppController.php(40): yii\console\Application->runAction('rbac-migrate/up', Array)
#13 [internal function]: console\controllers\AppController->actionSetup()
#14 /app/path/app-name/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)
#15 /app/path/app-name/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\InlineAction->runWithParams(Array)
#16 /app/path/app-name/vendor/yiisoft/yii2/console/Controller.php(127): yii\base\Controller->runAction('setup', Array)
#17 /app/path/app-name/vendor/yiisoft/yii2/base/Module.php(454): yii\console\Controller->runAction('setup', Array)
#18 /app/path/app-name/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('app/setup', Array)
#19 /app/path/app-name/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('app/setup', Array)
#20 /app/path/app-name/vendor/yiisoft/yii2/base/Application.php(375): yii\console\Application->handleRequest(Object(yii\console\Request))
#21 /app/path/app-name/tests/codeception/bin/yii(22): yii\base\Application->run()
#22 {main}
[vagrant@localhost app-name]$ 
```

**Comment by XzAeRo** [comment]
The error is quite clear: `Exception: SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'article_category' already exists`

Please check your `.env` settings, specifically the `DB_DSN` and `TEST_DB_DSN` values, and set a **different** databases for each suite.

**Comment by davidjeddy** [comment]
# Framework
# ---------
To revisit this I have just attempted a 100% clean install; the DB is completely empty before running the migration command:

```
ubuntu@ip-{ADDR OMITTED}:/usr/share/nginx/html$ php console/yii app/setup
Setting writable: /usr/share/nginx/html/common/runtime
Setting writable: /usr/share/nginx/html/frontend/runtime
Setting writable: /usr/share/nginx/html/frontend/web/assets
Setting writable: /usr/share/nginx/html/backend/runtime
Setting writable: /usr/share/nginx/html/backend/web/assets
Setting writable: /usr/share/nginx/html/storage/cache
Setting writable: /usr/share/nginx/html/storage/web/source
Setting executable: /usr/share/nginx/html/backend/yii
Setting executable: /usr/share/nginx/html/frontend/yii
Setting executable: /usr/share/nginx/html/console/yii
Generating keys in /usr/share/nginx/html/.env
Yii Migration Tool (based on Yii v2.0.11.2)

Creating migration history table "system_db_migration"...Done.
Total 15 new migrations to be applied:
	m140703_123000_user
	m140703_123055_log
	m140703_123104_page
	m140703_123803_article
	m140703_123813_rbac
	m140709_173306_widget_menu
	m140709_173333_widget_text
	m140712_123329_widget_carousel
	m140805_084745_key_storage_item
	m141012_101932_i18n_tables
	m150318_213934_file_storage_item
	m150414_195800_timeline_event
	m150725_192740_seed_data
	m150929_074021_article_attachment_order
	m160203_095604_user_token

Apply the above migrations? (yes|no) [no]:yes
*** applying m140703_123000_user
    > create table {{%user}} ... done (time: 0.020s)
    > create table {{%user_profile}} ... done (time: 0.021s)
    > add foreign key fk_user: {{%user_profile}} (user_id) references {{%user}} (id) ... done (time: 0.035s)
*** applied m140703_123000_user (time: 0.092s)

*** applying m140703_123055_log
    > create table {{%system_log}} ... done (time: 0.018s)
    > create index idx_log_level on {{%system_log}} (level) ... done (time: 0.021s)
    > create index idx_log_category on {{%system_log}} (category) ... done (time: 0.021s)
*** applied m140703_123055_log (time: 0.069s)

*** applying m140703_123104_page
    > create table {{%page}} ... done (time: 0.021s)
*** applied m140703_123104_page (time: 0.028s)

*** applying m140703_123803_article
    > create table {{%article_category}} ... done (time: 0.017s)
    > create table {{%article}} ... done (time: 0.033s)
    > create table {{%article_attachment}} ... done (time: 0.027s)
    > add foreign key fk_article_attachment_article: {{%article_attachment}} (article_id) references {{%article}} (id) ... done (time: 0.035s)
    > add foreign key fk_article_author: {{%article}} (created_by) references {{%user}} (id) ... done (time: 0.036s)
    > add foreign key fk_article_updater: {{%article}} (updated_by) references {{%user}} (id) ... done (time: 0.038s)
    > add foreign key fk_article_category: {{%article}} (category_id) references {{%article_category}} (id) ... done (time: 0.043s)
    > add foreign key fk_article_category_section: {{%article_category}} (parent_id) references {{%article_category}} (id) ... done (time: 0.035s)
    > create unique index idx_article_slug on {{%article}} (slug) ...Exception: SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes
The SQL being executed was: ALTER TABLE `article` ADD UNIQUE INDEX `idx_article_slug` (`slug`) (/usr/share/nginx/html/vendor/yiisoft/yii2/db/Schema.php:636)
#0 /usr/share/nginx/html/vendor/yiisoft/yii2/db/Command.php(856): yii\db\Schema->convertException(Object(PDOException), 'ALTER TABLE `ar...')
#1 /usr/share/nginx/html/vendor/yiisoft/yii2/db/Migration.php(458): yii\db\Command->execute()
#2 /usr/share/nginx/html/common/migrations/db/m140703_123803_article.php(59): yii\db\Migration->createIndex('idx_article_slu...', '{{%article}}', 'slug', true)
#3 /usr/share/nginx/html/vendor/yiisoft/yii2/db/Migration.php(96): m140703_123803_article->safeUp()
#4 /usr/share/nginx/html/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(654): yii\db\Migration->up()
#5 /usr/share/nginx/html/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(166): yii\console\controllers\BaseMigrateController->migrateUp('m140703_123803_...')
#6 [internal function]: yii\console\controllers\BaseMigrateController->actionUp(0)
#7 /usr/share/nginx/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#8 /usr/share/nginx/html/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\InlineAction->runWithParams(Array)
#9 /usr/share/nginx/html/vendor/yiisoft/yii2/console/Controller.php(128): yii\base\Controller->runAction('up', Array)
#10 /usr/share/nginx/html/vendor/yiisoft/yii2/base/Module.php(523): yii\console\Controller->runAction('up', Array)
#11 /usr/share/nginx/html/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/up', Array)
#12 /usr/share/nginx/html/console/controllers/AppController.php(39): yii\console\Application->runAction('migrate/up', Array)
#13 [internal function]: console\controllers\AppController->actionSetup()
#14 /usr/share/nginx/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#15 /usr/share/nginx/html/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\InlineAction->runWithParams(Array)
#16 /usr/share/nginx/html/vendor/yiisoft/yii2/console/Controller.php(128): yii\base\Controller->runAction('setup', Array)
#17 /usr/share/nginx/html/vendor/yiisoft/yii2/base/Module.php(523): yii\console\Controller->runAction('setup', Array)
#18 /usr/share/nginx/html/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('app/setup', Array)
#19 /usr/share/nginx/html/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('app/setup', Array)
#20 /usr/share/nginx/html/vendor/yiisoft/yii2/base/Application.php(380): yii\console\Application->handleRequest(Object(yii\console\Request))
#21 /usr/share/nginx/html/console/yii(26): yii\base\Application->run()
#22 {main}
*** failed to apply m140703_123803_article (time: 0.268s)


3 from 15 migrations were applied.

Migration failed. The rest of the migrations are canceled.
Yii Migration Tool (based on Yii v2.0.11.2)

Creating migration history table "system_rbac_migration"...Done.
Total 3 new migrations to be applied:
	m150625_214101_roles
	m150625_215624_init_permissions
	m151223_074604_edit_own_model

Apply the above migrations? (yes|no) [no]:yes
*** applying m150625_214101_roles
Exception 'yii\db\Exception' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'zfg_int.rbac_auth_assignment' doesn't exist
The SQL being executed was: DELETE FROM `rbac_auth_assignment`'

in /usr/share/nginx/html/vendor/yiisoft/yii2/db/Schema.php:636

Error Info:
Array
(
    [0] => 42S02
    [1] => 1146
    [2] => Table 'zfg_int.rbac_auth_assignment' doesn't exist
)

Stack trace:
#0 /usr/share/nginx/html/vendor/yiisoft/yii2/db/Command.php(856): yii\db\Schema->convertException(Object(PDOException), 'DELETE FROM `rb...')
#1 /usr/share/nginx/html/vendor/yiisoft/yii2/rbac/DbManager.php(956): yii\db\Command->execute()
#2 /usr/share/nginx/html/vendor/yiisoft/yii2/rbac/DbManager.php(882): yii\rbac\DbManager->removeAllAssignments()
#3 /usr/share/nginx/html/common/migrations/rbac/m150625_214101_roles.php(10): yii\rbac\DbManager->removeAll()
#4 /usr/share/nginx/html/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(654): m150625_214101_roles->up()
#5 /usr/share/nginx/html/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(166): yii\console\controllers\BaseMigrateController->migrateUp('m150625_214101_...')
#6 [internal function]: yii\console\controllers\BaseMigrateController->actionUp(0)
#7 /usr/share/nginx/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#8 /usr/share/nginx/html/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\InlineAction->runWithParams(Array)
#9 /usr/share/nginx/html/vendor/yiisoft/yii2/console/Controller.php(128): yii\base\Controller->runAction('up', Array)
#10 /usr/share/nginx/html/vendor/yiisoft/yii2/base/Module.php(523): yii\console\Controller->runAction('up', Array)
#11 /usr/share/nginx/html/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('rbac-migrate/up', Array)
#12 /usr/share/nginx/html/console/controllers/AppController.php(40): yii\console\Application->runAction('rbac-migrate/up', Array)
#13 [internal function]: console\controllers\AppController->actionSetup()
#14 /usr/share/nginx/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#15 /usr/share/nginx/html/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\InlineAction->runWithParams(Array)
#16 /usr/share/nginx/html/vendor/yiisoft/yii2/console/Controller.php(128): yii\base\Controller->runAction('setup', Array)
#17 /usr/share/nginx/html/vendor/yiisoft/yii2/base/Module.php(523): yii\console\Controller->runAction('setup', Array)
#18 /usr/share/nginx/html/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('app/setup', Array)
#19 /usr/share/nginx/html/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('app/setup', Array)
#20 /usr/share/nginx/html/vendor/yiisoft/yii2/base/Application.php(380): yii\console\Application->handleRequest(Object(yii\console\Request))
#21 /usr/share/nginx/html/console/yii(26): yii\base\Application->run()
#22 {main}
```
